zuul:
  route:
    student:
      id: Student
      path: /api/student/
      strip-prefix: true
    consumer:
      id: Consumer-Details
      path: /api/consumer/
      strip-prefix: true
server:
  port: 8080
spring:
  application:
    name: Zuul-Server
eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
